<a href="https://colab.research.google.com/github/subhayughoshal/Speech-to-text-model/blob/main/Huggingface_SpeechToText_Fixed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install transformers

In [ ]:
from transformers import pipeline

In [ ]:
import transformers
print(transformers.__version__)


4.53.0


In [ ]:
import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import numpy as np

In [ ]:
Tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
Model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
audio, sampling_rate= librosa.load("/V.m4a", sr=16000)

In [ ]:
audio, sampling_rate

(array([-3.9024367e-06, -3.4119654e-05, -3.2516814e-06, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00], dtype=float32),
 16000)

In [ ]:
display.Audio('/V.m4a', autoplay= True)

In [ ]:
input_values= Tokenizer(audio, return_tensors= 'pt').input_values
input_values

tensor([[-0.0003, -0.0006, -0.0003,  ..., -0.0003, -0.0003, -0.0003]])

In [ ]:
logits= Model(input_values).logits
logits

tensor([[[ 13.7819, -25.9714, -25.6292,  ...,  -5.9333,  -8.6897,  -6.3988],
         [ 13.7258, -26.0419, -25.7015,  ...,  -6.0284,  -8.7112,  -6.4778],
         [ 13.5979, -25.9882, -25.6520,  ...,  -6.1415,  -8.6579,  -6.5336],
         ...,
         [ 13.5548, -25.1543, -24.8220,  ...,  -5.2082,  -8.1536,  -5.7692],
         [ 13.6751, -25.3555, -25.0154,  ...,  -5.3765,  -8.4226,  -5.8729],
         [ 13.7334, -25.4985, -25.1533,  ...,  -5.5134,  -8.5770,  -5.9709]]],
       grad_fn=<ViewBackward0>)

In [ ]:
predicted_ids= torch.argmax(logits, dim=-1)


In [ ]:
transcriptions= Tokenizer.decode(predicted_ids[0])


In [ ]:
transcriptions

'HULLO AND WELCOME THIS IS AN A I VOICE MESSAGE'